### ISSUE TITLE
ImageDataBunch.from_lists - AttributeError: 'numpy.ndarray' object has no attribute 'read'

### ISSUE THREAD

**Issue by twosatnams** [fastai/fastai#1172]
**Describe the bug**

**To Reproduce**
```
photos_folder_path: str = f'./photos'
files: List[str] = [photos_folder_path + '/' + filename for filename in listdir(photos_folder_path)]
labels: List[str] = ['1', '2', '3', ... ]
data = ImageDataBunch.from_lists(photos_folder_path, files, labels=labels, tfms=get_transforms())
```

Produces the following error

```
  File "/Users/satnam/project/fodlername/lib/embeddings.py", line 24, in get_embeddings
    data = ImageDataBunch.from_lists(photos_folder_path, files, labels=['men', 'women'], tfms=get_transforms())
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/vision/data.py", line 141, in from_lists
    src = ImageItemList(fnames, path=path).random_split_by_pct(valid_pct).label_from_list(labels)
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/data_block.py", line 144, in random_split_by_pct
    return self.split_by_idx(rand_idx[:cut])
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/data_block.py", line 129, in split_by_idx
    return self.split_by_idxs(train_idx, valid_idx)
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/data_block.py", line 124, in split_by_idxs
    return self.split_by_list(self[train_idx], self[valid_idx])
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/data_block.py", line 79, in __getitem__
    if isinstance(try_int(idxs), int): return self.get(idxs)
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/vision/data.py", line 265, in get
    res = super().get(i)
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/data_block.py", line 56, in get
    return self.create_func(item) if self.create_func else item
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/fastai/vision/image.py", line 421, in open_image
    x = PIL.Image.open(fn).convert('RGB')
  File "/Users/satnam/.local/share/virtualenvs/project-teh7pUYM/lib/python3.7/site-packages/PIL/Image.py", line 2615, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'numpy.ndarray' object has no attribute 'read'
```

Following the stack trace, I found that the argument that was being passed to PIL.Image.open was a list with a single element (which points to one of the image files) instead of being a path to an image file. It was working fine with version 1.0.21, but started seeing issues with the newer versions. It can be reproduced in the latest version - 1.0.24

**Comment by sgugger** [comment]
I just tried your code and got a databunch without any error. Was this on master?

**Comment by twosatnams** [comment]
Very interesting! I've tried the same in three different machines and always get the error. I'm going to close the issue for now if you're not able to reproduce though. Will reopen when I have some concrete steps to reproduce

**Comment by abhiksark** [comment]
@twosatnams  facing the same issue, any idea how you resolved this issue
