### ISSUE TITLE
Support persistent workers

### ISSUE THREAD

**Issue by jph00** [fastai/fastai#2768]

**Comment by rraminen** [comment]
Is there any update on this issue? I came across the below error :
```
Traceback (most recent call last):
  File "05_pet_breeds.py", line 84, in <module>
    x,y = dls1.valid.one_batch()
  File "/root/fastai/fastai/data/load.py", line 136, in one_batch
    with self.fake_l.no_multiproc(): res = first(self)
  File "/usr/local/lib/python3.6/dist-packages/fastcore/foundation.py", line 187, in first
    try: return next(iter(x))
  File "/root/fastai/fastai/data/load.py", line 102, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 466, in __init__
    super(_SingleProcessDataLoaderIter, self).__init__(loader)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 415, in __init__
    self._persistent_workers = loader.persistent_workers
AttributeError: '_FakeLoader' object has no attribute 'persistent_workers'

```

**Comment by alexgalkin1994** [comment]
So, any update or workaround for this?

**Comment by undying** [comment]
"workaround" is to use pytorch 1.6.0 until this problem will be fixed

**Comment by alexgalkin1994** [comment]
> "workaround" is to use pytorch 1.6.0 until this problem will be fixed

The workaround for my other problem was to use pytorch 1.7.0 because 1.6.0 does not support the RTX 3080/ CUDA 11.

**Comment by jph00** [comment]
> So, any update or workaround for this?

@alexgalkin1994 don't do that. Not in this project, not in any open source project.

**Comment by alexgalkin1994** [comment]
> > So, any update or workaround for this?
> 
> @alexgalkin1994 don't do that. Not in this project, not in any open source project.

Hey, I didn't mean to offend, I only wanted to know if someone has a way to work around this issue in the meantime since I have to work with PyTorch 1.7.0.

**Comment by henry090** [comment]
I just have seen that they released torch's & torchvision's next release on PyPI.

**Comment by jph00** [comment]
Thanks for letting me know - I better get on to this then! :)

**Comment by sophigit** [comment]
I am wondering whether there is any update on this. I encountered the same issue and cannot finish course 1..Thanks much!

**Comment by rahit** [comment]
Having the same issue. Installed pytorch 1.6.0 although did not want to and then ended up with the following error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-02dd30090e2f> in <module>
     22 
     23 # import torch
---> 24 from fastai.tabular.all import *
     25 from fastai.data.all import *

F:\Anaconda3\envs\gemo\lib\site-packages\fastai\tabular\all.py in <module>
----> 1 from ..basics import *
      2 from ..callback.all import *
      3 from .core import *
      4 from .data import *
      5 from .model import *

F:\Anaconda3\envs\gemo\lib\site-packages\fastai\basics.py in <module>
----> 1 from .data.all import *
      2 from .optimizer import *
      3 from .callback.core import *
      4 from .learner import *
      5 from .metrics import *

F:\Anaconda3\envs\gemo\lib\site-packages\fastai\data\all.py in <module>
----> 1 from ..torch_basics import *
      2 from .core import *
      3 from .load import *
      4 from .external import *
      5 from .transforms import *

F:\Anaconda3\envs\gemo\lib\site-packages\fastai\torch_basics.py in <module>
----> 1 from torch import multiprocessing
      2 import platform,os
      3 if platform.system()=='Darwin':
      4     # Python 3.8 changed to 'spawn' but that doesn't work with PyTorch DataLoader w n_workers>0
      5     multiprocessing.set_start_method('fork', force=True)

F:\Anaconda3\envs\gemo\lib\site-packages\torch\__init__.py in <module>
    114                 err = ctypes.WinError(last_error)
    115                 err.strerror += ' Error loading "{}" or one of its dependencies.'.format(dll)
--> 116                 raise err
    117             elif res is not None:
    118                 is_loaded = True

OSError: [WinError 127] The specified procedure could not be found. Error loading "F:\Anaconda3\envs\gemo\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

**Comment by estaar** [comment]
Just update your Fast AI.
for pip:
pip install --upgrade fastai

**Comment by jph00** [comment]
Fixed now.
