### ISSUE TITLE
Install fastai for torch < 1.7

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai#3063]
I am having trouble getting a fastai to work with torch 1.6. and python 3.6 (I know, they are not the bleeding edge...)
- Need to install via `pip` 
- It is for a Nvidia docker container that only support torch 1.6 and python 3.6.

I have tried many combinations of
```
pip install "fastai<2.1"
```
or pinning to a version:
```
pip install "fastai==2.0.18"
```
with no success.
The problem is linked to not getting the good fastcore: (`log_args` is missing, or  'Image' has no attribute 'size').

Any working tips?

**Comment by tcapelle** [comment]
Ok, I tracked my issue, pillow was to old.
We should put min version on the `settings.ini` to avoid this.

**Comment by tyoc213** [comment]
Thes best way right now I can think of, is each time fastcore or fastai is released, in some place log the versions, like on a separate repo that pulls the libs and install them on clean environment, then outputs a log that commits the versions, maybe `test_utils.show_version` would help too and something like `pip freeze` or `conda list --export`... dont know if that will help in the future to "track correct versions"

**Comment by muellerzr** [comment]
Proper docker containers for fastai and fastcore that are updated daily are available here: https://hub.docker.com/r/fastdotai/fastai

See here for more information: https://github.com/fastai/docker-containers#fastai

@jph00 pretty sure we can close

**Comment by muellerzr** [comment]
Since fastai uses fastrelease, Jeremy and I discussed putting this option in there, and when calling `make release` (how fastai pushes new releases) we can create the versions.txt file (or something similar). Thanks @tyoc213 for the suggestion

**Comment by jph00** [comment]
Thanks all.

**Comment by tcapelle** [comment]
Ok, so right now it is not possible to install specific version of fastai, only latests. (at least with pip).
For me the simplest solution is to pin fastcore in fastai `settings.ini`. Most of the broken dependencies comes from `fastcore`  peace of change.
